from pathlib import Path
from typing import Protocol

from twitch_wap.domain.models import ChannelReadiness, Evidence


class TwitchDiscoveryPort(Protocol):
    def open_home(self) -> None: ...

    def open_search(self) -> None: ...

    def search(self, query: str) -> None: ...

    def scroll_results(self) -> None: ...

    def select_streamer(self) -> str: ...


class ChannelObservationPort(Protocol):
    def dismiss_known_interruptions(self) -> tuple[str, ...]: ...

    def wait_until_ready(self, channel_url: str) -> ChannelReadiness: ...


class EvidencePort(Protocol):
    def capture(self, channel_url: str, label: str = "channel") -> Evidence: ...

    def capture_failure(self, label: str, error: str) -> Path: ...
